#! /usr/bin/perl

$port = shift;

if (!$port) {
    die "usage: server port\n";
}

$js = <<EOF
var http = require('http');

var server = http.createServer(function(req,res) {
    res.writeHeader(200, {
        'Content-Type' : 'text/html'
    });

    var prog = req.url.replace(/\\?.*\$/, '').replace(/^[^\\/]*\\//, '');
    var args = req.url.replace(/^.*\\?/, '').split("&").join(" ");

    var exec = require('child_process').exec,
        child;

    var cmd = 'php ./' + prog + ' ' + args;

    child = exec(cmd,
                 function (error, stdout, stderr) {
                     res.end(stdout);
                 });


}).listen($port);
EOF
;

open(JS, ">server-tmp.js");
print JS $js;
close(JS);

system("node server-tmp.js");

unlink("server-tmp.js");
